### ISSUE TITLE
Adding support for functions

### ISSUE THREAD

**Issue by phayes** [tjardoo/openai-client#12]
Hi there, 

I'm thinking of implementing function calling (https://openai.com/blog/function-calling-and-other-api-updates), but I don't want to step on toes if this is already being implemented.   Are there any current plans to support function calling?  If not, I'll add support.

**Comment by tjardoo** [comment]
Hi. I'm not working on the implementation of the function calling yet (due to limited free time). Please feel free to create a PR and I'll merge it.
