### ISSUE TITLE
Why was the feature "Fine-tunes"  deprecated?

### ISSUE THREAD

**Issue by xiuno** [tjardoo/openai-client#15]
I think this is important!

**Comment by xiuno** [comment]
https://platform.openai.com/docs/guides/fine-tuning

```
This guide is intended for users of the new OpenAI fine-tuning API. If you are a legacy fine-tuning user, please refer to our [legacy fine-tuning guide](https://platform.openai.com/docs/guides/legacy-fine-tuning).
```

have a plan for fine-tuning?

**Comment by tjardoo** [comment]
It was marked deprecated to keep in sync with the API reference see https://platform.openai.com/docs/api-reference/fine-tunes. I'm working on the new Fine-tuning API endpoint. I just created a new issue for that #16.
