### ISSUE TITLE
Feature Request: Expose OpenAI Rate Limiting Headers

### ISSUE THREAD

**Issue by democai** [tjardoo/openai-client#33]
I'm currently using openai_dive in a project to simplify my usage of the OpenAI API.. One thing that might be useful to the wider user base would be access to the Rate Limiting Headers as described in the [OpenAI Docs](https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers) specifically they mention `x-ratelimit-limit-requests`, `x-ratelimit-limit-tokens`,`x-ratelimit-remaining-requests`,`x-ratelimit-remaining-tokens`,`x-ratelimit-reset-requests`, and `x-ratelimit-reset-tokens`.  Those all sound very useful for backing off the API appropriately.
Would you consider exposing the return headers in the various response objects?

**Comment by tjardoo** [comment]
Yes this is still on the to-do list. But feel free to create a PR.
