### ISSUE TITLE
bug: openai dive crashes server if there is a network error

### ISSUE THREAD

**Issue by densumesh** [tjardoo/openai-client#66]
Whenever OpenAI returns a 502 or doesn't respond over the network, an unwrap within the dive client fails and crashes our entire web server.  We are currently on openai-dive 0.4.6

![image](https://github.com/tjardoo/openai-client/assets/25559111/4ce13a59-ec4d-46eb-9dfd-d2a82fa9670a)

The fix is probably changing the unwrap at https://github.com/tjardoo/openai-client/blob/962d0fa5c4c69554e8ca02b6de2b8fa6fc8ae3bd/src/v1/api.rs#L123 to be an unwrap_or or adding other error handling and retry logic. 

We may get to pring this soon, but wanted to create the issue for visibility.

**Comment by tjardoo** [comment]
Thanks for reporting! Feel free to create a PR - changing the `unwrap()` function seems to me indeed the correct approach.
