### ISSUE TITLE
`APIError::EndpointError` should include status code

### ISSUE THREAD

**Issue by philpax** [tjardoo/openai-client#72]
At present, `EndpointError` is constructed using just the text of the response: https://github.com/tjardoo/openai-client/blob/b99e9f7714a68a19192f5091acc4b425c995d3d8/src/v1/helpers.rs#L14-L16

Ideally, this would also return the status code so that the calling code can decide what to do with the failure (i.e. if it's a 5xx error, the request could be retried; if it's a rate limit, the code could wait a bit.)

I'm also not sure `validate_response` (below that code) is called anywhere, and given that `check_status_code` will return an `EndpointError` for any successful responses, it's not clear that there *could* be an opportunity for it to be called. It seems like these two functions should be merged so that specific errors from the OpenAI API can be surfaced, while non-specific errors can be dealt with based on the status code.

**Comment by tjardoo** [comment]
In the endpoint methods the method `format_response` is called to build the struct from the response. In that method the `validate_response` method is called to validate the response - in some cases the endpoint returns a 200 status code but with only 1 field called `error`. This method is there to catch that. In all other cases the `check_status_code` method will handle it.

**Comment by philpax** [comment]
Ah, you're right - GitHub code search let me down. Cool, your fix looks great, then! 🙂 

If possible, would it be possible to add another error for `RateLimitExceeded`? That occurs when `InvalidRequestError::code == "rate_limit_exceeded"`. My custom client currently catches this by making the request and trying to deserialise `{error: InvalidRequest}`; `validate_response` might flatten the JSON into a string, which makes this a bit more difficult.

For reference, this is what our current error handling logic looks like:
```rust
use openai_dive::v1::{
    error::InvalidRequestError,
    resources::{chat, shared},
};


#[derive(Serialize, Deserialize)]
struct ErrorResponse {
    error: InvalidRequestError,
}

let reqwest_response = self
    .client
    .post("https://api.openai.com/v1/chat/completions")
    .json(&request_model)
    .header(AUTHORIZATION, format!("Bearer {}", self.token))
    .send()
    .await
    .map_err(LlmError::ServerError)?;

let status = reqwest_response.status();
if status == StatusCode::INTERNAL_SERVER_ERROR
    || status == StatusCode::BAD_GATEWAY
    || status == StatusCode::SERVICE_UNAVAILABLE
    || status == StatusCode::GATEWAY_TIMEOUT
{
    return Err(LlmError::InternalServerError(status));
}
let text = reqwest_response.text().await.map_err(LlmError::ServerError)?;

if status != StatusCode::OK {
    if let Ok(err) = serde_json::from_str::<ErrorResponse>(&text) {
        if err.error.code == "rate_limit_exceeded" {
            return Err(LlmError::RateLimitExceeded(err.error.message));
        }
        return Err(LlmError::UnknownApiError(err.error.message));
    }

    return Err(LlmError::UnknownApiError(text));
}
```

**Comment by tjardoo** [comment]
@philpax thanks for the suggestion. I've added `AuthenticationError` and `RateLimitError` in #73 - what do you think of this setup?

**Comment by tjardoo** [comment]
Thanks!
